import type { LocaleContent } from '../types.ts';

export default {
  seo: { title: 'YT Thumbnail Downloader – Download YouTube Thumbnails', description: 'Download YouTube thumbnails in the highest available quality. Paste a video or Shorts link, preview the available sizes, and save the original JPG. Free, no sign-up.' },
  nav: { skip: 'Skip to content', home: 'Downloader', how: 'How it works', faq: 'FAQ', about: 'About', privacy: 'Privacy', terms: 'Terms', mainLabel: 'Main navigation', footerLabel: 'Footer navigation', language: 'Language', footerTagline: 'A little tool for the bigger picture.', disclaimer: 'Independent tool. Not affiliated with YouTube.', back: 'Back to downloader' },
  home: {
    eyebrow: 'A free tool for creators & the curious', h1: 'YT Thumbnail Downloader', subtitle: 'Get the thumbnail behind any YouTube video.', description: 'Paste a link. Pick your size. Save the original image. No account, no installs, no extra steps.',
    toolTitle: 'Your next thumbnail starts here', toolDescription: 'A YouTube video, Short, or live video link.', inputLabel: 'YouTube video link', inputPlaceholder: 'Paste a YouTube link or video ID', submit: 'Get thumbnails', inputHelp: 'Supports youtube.com & youtu.be links', example: 'Try an example', noscript: 'Enable JavaScript to find and download thumbnails. The guides below are available without it.', trust: ['Original JPG files', 'Highest available quality', 'Works in your browser'],
    resultsEyebrow: 'Ready for a closer look', resultsTitle: 'Your thumbnail', clear: 'Clear result', previewAlt: 'YouTube video thumbnail preview', fileType: 'JPG · Original image', chooseSize: 'Choose a size', download: 'Download JPG', open: 'Open image', copy: 'Copy image link', saveHint: 'On mobile, you can also open the image and touch and hold to save it.', copyLabel: 'Copy this image link',
    howEyebrow: 'From link to image', howTitle: 'Three steps. One great thumbnail.', howIntro: 'Keep a copy of your own artwork, collect a reference with permission, or take a closer look at the details.',
    steps: [
      { title: 'Copy the video link', body: 'Open a YouTube video or Short and copy its link from the address bar or Share menu.' },
      { title: 'Find your thumbnail', body: 'Paste the link above. We check the available images and show the largest version first.' },
      { title: 'Pick a size & save', body: 'Preview the available sizes, then download the original JPG straight to your device.' },
    ],
    sizesEyebrow: 'A little clarity on quality', sizesTitle: 'The right size. The original pixels.', sizesIntro: 'YouTube makes thumbnails available in several sizes. We find what exists and keep the image exactly as it is.', tableCaption: 'Common YouTube thumbnail sizes', qualityColumn: 'Quality', sizeColumn: 'Typical size', sizesNote: 'Not every video has every size. Your results show the actual dimensions, with the highest available quality selected.', sizesFootnote: 'No upscaling. No cropping. No added watermarks.',
    faqEyebrow: 'Good to know', faqTitle: 'A few common questions.', faqIntro: 'A little help with links, image quality, and saving your thumbnails.',
    faqs: [
      { question: 'How do I download a YouTube thumbnail?', answer: 'Copy the video link from YouTube, paste it into the field above, and select Get thumbnails. Choose an available size, then select Download JPG. You will get the original image at the displayed resolution, with no resizing or added watermark.' },
      { question: 'Can I download HD YouTube thumbnails?', answer: 'Yes, when the video has a high-resolution thumbnail. The largest common version is 1280 × 720 pixels, but availability varies by video. This tool checks the available images and selects the largest one it finds. It does not upscale a smaller image.' },
      { question: 'Does this work with YouTube Shorts?', answer: 'Yes. Paste a youtube.com/shorts/ link just like a regular video link. We retrieve the thumbnail images YouTube makes available for that video. Their shape and crop may differ from the vertical preview shown in the Shorts feed.' },
      { question: 'Why is the highest-resolution image missing?', answer: 'Some videos, especially older uploads, do not have every thumbnail size. We show only the versions that load successfully. If Max resolution is missing, choose the largest available option instead.' },
      { question: 'How do I save a thumbnail on my phone?', answer: 'Tap Download JPG and follow your browser’s download prompt. If your browser opens the image instead, use its save or share option. You can also select Open image, then touch and hold the picture to save it. The exact steps depend on your browser.' },
      { question: 'What links can I use?', answer: 'You can use standard YouTube watch links, youtu.be short links, Shorts, live video links, and embedded video links. An 11-character video ID works too. Links to channels or playlists without a specific video are not supported.' },
      { question: 'Are my links saved?', answer: 'The downloader has no personal search-history feature. Your browser reads the video ID locally and requests images directly from YouTube’s image servers. We also use Microsoft Clarity to understand site interactions. Our Privacy page explains these requests and analytics.', privacyLink: true },
      { question: 'Can I reuse the thumbnails I download?', answer: 'Downloading an image does not transfer the rights to it. For reuse, make sure you own the image, have permission, or have another valid basis for using it. This tool is independent of YouTube and the video creators.' },
    ], privacyLink: 'Read our privacy policy.', closing: 'Small tool. Original images. Always free to use.',
  },
  client: {
    invalidInput: 'Enter a valid YouTube video URL or an 11-character video ID.', loading: 'Loading thumbnails…', checking: 'Checking the available thumbnail sizes…', timeout: 'The request timed out. Check your connection and try again.', noResults: 'No thumbnail could be loaded. Check the video link and your connection, then try again.', networkError: 'The thumbnails could not be loaded. Check your connection and try again.',
    previewAlt: 'YouTube video thumbnail for {id}, {width} by {height} pixels', selected: '{quality} selected: {width} × {height} pixels. Ready to download.', selectedFallback: '{quality} preview ready: {width} × {height} pixels. Open the image to save it in your browser.', found: 'Available sizes: {count}. The largest image is selected: {width} × {height} pixels. Ready to download.', foundFallback: 'Available sizes: {count}. Preview ready. Open the image to save it in your browser.', copied: 'Copied', copySuccess: 'Image link copied.', copyFailed: 'Copy is unavailable. The image link is selected below; copy it manually.', reset: 'Ready for another YouTube video link.', download: 'Download JPG', openToSave: 'Open image to save', qualities: { maxres: 'Max resolution', standard: 'Standard', high: 'High quality', medium: 'Medium' },
  },
  documents: {
    about: {
      title: 'About – YT Thumbnail Downloader', description: 'Learn how YT Thumbnail Downloader finds available YouTube thumbnail images in your browser, with no account or API key.', eyebrow: 'About the tool', h1: 'A simpler way to find a video’s thumbnail.', lead: 'YT Thumbnail Downloader helps you preview and save the thumbnail images available for a YouTube video, all from your browser.',
      sections: [
        { heading: 'Paste a link. Choose a size.', paragraphs: ['Use a regular YouTube video link, a youtu.be short link, a Shorts, Live, or Embed link, or an 11-character video ID. The tool checks YouTube’s image CDN for available JPG thumbnails and selects the highest resolution it can find.', 'Not every video has a high-resolution thumbnail. The results show each available image’s actual dimensions so you can choose a useful size without guessing.'] },
        { heading: 'The original image, without extra steps', paragraphs: ['Downloads use the JPG supplied by YouTube’s image CDN. The tool does not upscale, crop, or add a watermark. You do not need an account, a YouTube API key, or a browser extension.', 'When browser restrictions prevent a direct download, you can open the original image and save it using your browser’s image menu.'] },
        { heading: 'Built for a small, useful job', paragraphs: ['This is a free, independent tool for creators and anyone who needs to inspect a thumbnail. It does not download videos, retrieve private content, or grant rights to an image.', 'YT Thumbnail Downloader is not affiliated with or endorsed by YouTube or Google.'] },
      ],
    },
    privacy: {
      title: 'Privacy – YT Thumbnail Downloader', description: 'How YT Thumbnail Downloader handles video links, image requests, Microsoft Clarity analytics, clipboard access, and hosting data.', eyebrow: 'Privacy', h1: 'What happens to your link.', lead: 'Thumbnail lookups run in your browser. The site has no accounts or personal search-history feature. We use Microsoft Clarity to understand how visitors interact with the site.',
      sections: [
        { heading: 'Video links and image requests', paragraphs: ['Your browser parses the link you enter to extract a YouTube video ID. To find and display thumbnails, it requests images directly from i.ytimg.com, YouTube’s image CDN. The video ID is part of each image URL.', 'Those requests expose standard connection information, such as your IP address, to the image provider. YouTube and Google handle their services under their own privacy policies. Pasting a link here does not make the request anonymous.'] },
        { heading: 'Local browser actions', paragraphs: ['The downloader does not maintain a personal history of your thumbnail lookups. The current result remains in page memory while the page is open. Your browser may cache images or keep a downloaded file according to its own settings. The analytics described below may also process page content and interactions.', 'The copy-image-link button writes the selected image URL to your clipboard only when you click it. The tool does not read your clipboard.'] },
        { heading: 'Microsoft Clarity analytics', paragraphs: ['We use Microsoft Clarity to understand visitor interactions through heatmaps and session replay. Clarity may use cookies and collect usage, device, browser, and interaction information, including information about the pages you visit and how you use them.', 'Microsoft processes this information under its own policies.'], link: { label: 'Microsoft Privacy Statement', url: 'https://privacy.microsoft.com/privacystatement' } },
        { heading: 'Hosting and site data', paragraphs: ['Cloudflare hosts this site and may process standard request logs and connection information to deliver and secure it. Hosting requests are separate from the thumbnail requests your browser sends to YouTube’s image CDN.', 'This version has no advertising or sign-in. Hosting and analytics providers may process information under their own policies.'] },
        { heading: 'Policy updates', paragraphs: ['If the way this tool handles data changes, this page will be updated to describe it.'] },
      ], updated: 'Last updated: October 4, 2026.',
    },
    terms: {
      title: 'Terms of Use – YT Thumbnail Downloader', description: 'Simple terms for using YT Thumbnail Downloader, including image rights, availability, and our independent status.', eyebrow: 'Terms of use', h1: 'Use the tool. Respect the work.', lead: 'YT Thumbnail Downloader is a free tool for finding thumbnail images available from YouTube’s image CDN. Please use it responsibly.',
      sections: [
        { heading: 'Image rights stay with their owners', paragraphs: ['Being able to view or download a thumbnail does not give you permission to republish it, use it commercially, or claim it as your own. Use images you own, have permission to use, or are otherwise entitled to use under the rules that apply to you.', 'You are responsible for how you use a downloaded image and for following applicable laws and platform terms.'] },
        { heading: 'Availability and limitations', paragraphs: ['The tool relies on images supplied by YouTube. A thumbnail may be unavailable, change over time, or exist only at a smaller size. Browser and network restrictions can also affect previews and downloads.', 'We aim to keep the tool useful, but do not promise uninterrupted access or a particular image resolution. Features may change as browser behavior and image availability change.'] },
        { heading: 'Reasonable use', paragraphs: ['Do not use this site to bypass access restrictions, interfere with the service, or infringe someone else’s rights. It is designed for individual thumbnail lookups and does not provide access to private videos or download video files.'] },
        { heading: 'An independent service', paragraphs: ['YT Thumbnail Downloader is not affiliated with, sponsored by, or endorsed by YouTube or Google. YouTube and other product names belong to their respective owners.'] },
      ], updated: 'Last updated: October 4, 2026.',
    },
  },
  notFound: { title: 'Page Not Found – YT Thumbnail Downloader', description: 'This page could not be found. Return to YT Thumbnail Downloader to find and save a YouTube thumbnail.', eyebrow: '404 · Page not found', h1: 'This page isn’t here.', lead: 'The address may be mistyped, or the page may have moved. The thumbnail downloader is one click away.' },
} satisfies LocaleContent;
