import type { LocaleContent } from '../types.ts';

export default {
  seo: { title: 'YT Thumbnail Downloader – Free YouTube Thumbnail Downloads', description: 'Use YT Thumbnail Downloader to preview and download YouTube thumbnails as JPGs. Supports video and Shorts links. Free, no sign-up or installation.' },
  nav: { skip: 'Skip to content', home: 'Downloader', how: 'How it works', faq: 'FAQ', about: 'About', privacy: 'Privacy', terms: 'Terms', mainLabel: 'Main navigation', footerLabel: 'Footer navigation', language: 'Language', footerTagline: 'A little tool for the bigger picture.', disclaimer: 'Independent tool. Not affiliated with YouTube.', back: 'Back to downloader' },
  home: {
    eyebrow: 'A free tool for creators & the curious', h1: 'Free YT Thumbnail Downloader', subtitle: 'Download YouTube thumbnails as original JPGs.', description: 'YT Thumbnail Downloader helps you preview and save the thumbnail images available for a YouTube video. Paste a video or Shorts link, compare the available sizes, and download the JPG that suits your needs. The tool selects the largest image it can load and shows its actual dimensions. It is free to use, with no account or installation required.',
    toolTitle: 'Paste a YouTube link to download its thumbnail', toolDescription: 'Enter a video, Shorts, or live video link, or an 11-character video ID.', inputLabel: 'YouTube video link', inputPlaceholder: 'Paste a YouTube link or video ID', submit: 'Get thumbnails', inputHelp: 'Supports youtube.com & youtu.be links', example: 'Try an example', noscript: 'Enable JavaScript to find and download thumbnails. The guides below are available without it.', trust: ['Original JPG files', 'Highest available quality', 'Works in your browser'],
    resultsEyebrow: 'Ready for a closer look', resultsTitle: 'Preview and download your YouTube thumbnail', clear: 'Clear result', previewAlt: 'YouTube video thumbnail preview', fileType: 'JPG · Original image', chooseSize: 'Choose a size', download: 'Download JPG', open: 'Open image', copy: 'Copy image link', saveHint: 'On mobile, you can also open the image and touch and hold to save it.', copyLabel: 'Copy this image link',
    howEyebrow: 'From link to image', howTitle: 'How to use YT Thumbnail Downloader', howIntro: 'Use the preview to check the artwork and choose a useful image size before saving. These three steps work on desktop and mobile browsers.',
    steps: [
      { title: 'Copy a YouTube video or Shorts link', body: 'Open the video on YouTube and copy its address, or use the Share menu in the YouTube app. You do not need to remove timestamps or sharing parameters. The link must identify one video: a channel address or a playlist link without a video ID will not work.' },
      { title: 'Preview the available YouTube thumbnails', body: 'Paste the link into the field above and select Get thumbnails. The downloader checks four common thumbnail versions and lists the images that load successfully. The largest available image is selected first. Look at the preview and the displayed pixel dimensions before choosing a version.' },
      { title: 'Choose a thumbnail size and save the JPG', body: 'Select a size, then use Download JPG to save the original file. If a browser restriction prevents a direct download, the button changes to Open image to save. Use that option to open the thumbnail and save it through your browser. Copy image link provides the selected image’s source URL.' },
    ],
    sizesEyebrow: 'A little clarity on quality', sizesTitle: 'YouTube thumbnail sizes and image quality', sizesIntro: 'A YouTube thumbnail downloader can only retrieve the images YouTube makes available. Different versions can have different dimensions and framing, so compare the preview as well as the size. The table lists common dimensions, while the download results show the actual width and height of each image found.', tableCaption: 'Common YouTube thumbnail sizes', qualityColumn: 'Quality', sizeColumn: 'Typical size', sizesNote: 'Choose the largest available thumbnail when you need to inspect small text or artwork. A smaller version may be enough for a compact reference. For layouts with a fixed aspect ratio, check the image’s proportions first: the common sizes include both 16:9 and 4:3 versions.', sizesFootnote: 'Not every video has every size, and an HD video does not guarantee an HD thumbnail. If the largest version is unavailable, use the best available result. Downloads preserve the supplied JPG; the tool does not upscale, crop, remove an existing watermark, or add its own.',
    linkGuide: {
      title: 'Supported YouTube thumbnail links', intro: 'Use a link that identifies a single video. Standard watch links, short share links, Shorts, live video links, and embedded video links are supported. You can also paste the video’s 11-character ID without a full URL.',
      caption: 'Supported YouTube video link formats', typeColumn: 'Link type', exampleColumn: 'Example',
      rowLabels: { watch: 'Watch', share: 'Share', shorts: 'Shorts', live: 'Live', embed: 'Embed', videoId: 'Video ID' }, videoIdExample: 'The 11-character value from the video link',
      paragraphs: [
        'In these examples, VIDEO_ID is a placeholder for the real ID. A watch link may also contain a playlist or a timestamp; the downloader uses the video ID and looks up that video’s thumbnail. It does not download every thumbnail in a playlist or channel.',
        'For Shorts, the thumbnail supplied by YouTube may differ from the vertical preview in the Shorts feed. A smaller image or a different crop can be the version available from the image server. This tool retrieves those supplied files and does not create a new vertical cover or extract a frame from the video.',
      ],
    },
    downloadHelp: {
      title: 'Troubleshooting YouTube thumbnail downloads', intro: 'If a thumbnail does not appear or cannot be saved, start with the link, the available image sizes, and your browser’s download options.',
      items: [
        { title: 'The link is rejected', body: 'Copy the address of a specific YouTube video and paste it again. Channel pages, profile links, and playlist-only links do not identify a supported video. If you enter a video ID directly, check that all 11 characters are present. Remove accidental spaces inside the link.' },
        { title: 'No thumbnail or HD image is available', body: 'A valid link does not guarantee that a thumbnail can be loaded. Check your connection and retry; browser or network restrictions can prevent requests to YouTube’s image servers. If some sizes appear but Max resolution is absent, choose the largest listed version. Available thumbnail files can change over time.' },
        { title: 'The image opens instead of downloading', body: 'Use your browser’s save-image option when the thumbnail opens in a new tab. On a phone, touch and hold the image to find the available save or share actions. Browser menus vary, so check the browser’s download list or your device’s files app if the saved JPG is not immediately visible.' },
      ],
    },
    faqEyebrow: 'Good to know', faqTitle: 'YT Thumbnail Downloader FAQ', faqIntro: 'Answers about thumbnail quality, supported links, saving files, and how the tool handles your video link.',
    faqs: [
      { question: 'Is YT Thumbnail Downloader free?', answer: 'Yes. You can preview and download the available thumbnail images without creating an account, installing software, or providing a YouTube API key. JavaScript must be enabled for the downloader to work; the instructions and size guide remain readable without it.' },
      { question: 'Can I download HD YouTube thumbnails?', answer: 'Yes, when YouTube supplies an HD version for the video. A common Max resolution thumbnail is 1280 × 720 pixels. Check the dimensions shown in your results; a quality label alone does not guarantee a particular resolution. The tool does not enlarge smaller images.' },
      { question: 'Does the downloader support YouTube Shorts?', answer: 'Yes. Paste the Shorts link into the same field used for regular videos. The tool checks the thumbnail files available for that video ID. Their shape or framing may differ from the vertical image displayed in the Shorts feed.' },
      { question: 'Which YouTube links can I paste?', answer: 'Use a watch, youtu.be, Shorts, live, or embed link, or an 11-character video ID. The supported-links guide above shows examples. A playlist link works only when it also identifies a specific video; the tool processes one video per lookup.' },
      { question: 'Why is the highest-resolution thumbnail missing?', answer: 'YouTube may not provide that version for the video, or the image request may fail. The downloader displays the versions it can load. Try again after checking your connection, or use the largest available image instead of expecting an upscaled replacement.' },
      { question: 'How do I save a YouTube thumbnail on mobile?', answer: 'Select a thumbnail size and tap Download JPG. If the button opens the image, use your browser’s save or share menu. Open image is also available beside the download control. The troubleshooting guide above explains the fallback when direct downloading is unavailable.' },
      { question: 'Are my video links saved?', answer: 'The downloader has no personal search-history feature. Your browser reads the video ID locally and requests images from YouTube’s image servers. We use Microsoft Clarity and Cloudflare Web Analytics to understand site use.', privacyLink: true },
      { question: 'Can I reuse a downloaded thumbnail?', answer: 'Downloading a thumbnail does not transfer ownership or permission to reuse it. Use images you own, have permission to reuse, or have another valid basis to use. The tool is independent of YouTube.' },
    ], privacyLink: 'Read our privacy policy for details about requests, analytics, and provider data handling.', closing: 'Free thumbnail downloads. Original JPG files. No sign-up.',
  },
  client: {
    invalidInput: 'Enter a valid YouTube video URL or an 11-character video ID.', loading: 'Loading thumbnails…', checking: 'Checking the available thumbnail sizes…', timeout: 'The request timed out. Check your connection and try again.', noResults: 'No thumbnail could be loaded. Check the video link and your connection, then try again.', networkError: 'The thumbnails could not be loaded. Check your connection and try again.',
    previewAlt: 'YouTube video thumbnail for {id}, {width} by {height} pixels', selected: '{quality} selected: {width} × {height} pixels. Ready to download.', selectedFallback: '{quality} preview ready: {width} × {height} pixels. Open the image to save it in your browser.', found: 'Available sizes: {count}. The largest image is selected: {width} × {height} pixels. Ready to download.', foundFallback: 'Available sizes: {count}. Preview ready. Open the image to save it in your browser.', copied: 'Copied', copySuccess: 'Image link copied.', copyFailed: 'Copy is unavailable. The image link is selected below; copy it manually.', reset: 'Ready for another YouTube video link.', download: 'Download JPG', openToSave: 'Open image to save', qualities: { maxres: 'Max resolution', standard: 'Standard', high: 'High quality', medium: 'Medium' },
  },
  documents: {
    about: {
      title: 'About – YT Thumbnail Downloader', description: 'Learn how YT Thumbnail Downloader finds available YouTube thumbnail images in your browser, with no account or API key.', eyebrow: 'About the tool', h1: 'A simpler way to find a video’s thumbnail.', lead: 'YT Thumbnail Downloader helps you preview and save the thumbnail images available for a YouTube video, all from your browser.',
      sections: [
        { heading: 'Paste a link. Choose a size.', paragraphs: ['Use a regular YouTube video link, a youtu.be short link, a Shorts, Live, or Embed link, or an 11-character video ID. The tool checks YouTube’s image CDN for available JPG thumbnails and selects the highest resolution it can find.', 'Not every video has a high-resolution thumbnail. The results show each available image’s actual dimensions so you can choose a useful size without guessing.'] },
        { heading: 'The original image, without extra steps', paragraphs: ['Downloads use the JPG supplied by YouTube’s image CDN. The tool does not upscale, crop, or add a watermark. You do not need an account, a YouTube API key, or a browser extension.', 'When browser restrictions prevent a direct download, you can open the original image and save it using your browser’s image menu.'] },
        { heading: 'Built for a small, useful job', paragraphs: ['This is a free, independent tool for creators and anyone who needs to inspect a thumbnail. It does not download videos, retrieve private content, or grant rights to an image.', 'YT Thumbnail Downloader is not affiliated with or endorsed by YouTube or Google.'] },
      ],
    },
    privacy: {
      title: 'Privacy – YT Thumbnail Downloader', description: 'How we handle video links, analytics and hosting data, plus Google AdSense data use and privacy choices if ads are enabled.', eyebrow: 'Privacy', h1: 'What happens to your link.', lead: 'Thumbnail lookups run in your browser. The site has no accounts or personal search-history feature. We use Microsoft Clarity to understand how visitors interact with the site.',
      sections: [
        { heading: 'Video links and image requests', paragraphs: ['Your browser parses the link you enter to extract a YouTube video ID. To find and display thumbnails, it requests images directly from i.ytimg.com, YouTube’s image CDN. The video ID is part of each image URL.', 'Those requests expose standard connection information, such as your IP address, to the image provider. YouTube and Google handle their services under their own privacy policies. Pasting a link here does not make the request anonymous.'] },
        { heading: 'Local browser actions', paragraphs: ['The downloader does not maintain a personal history of your thumbnail lookups. The current result remains in page memory while the page is open. Your browser may cache images or keep a downloaded file according to its own settings. The analytics described below may also process page content and interactions.', 'The copy-image-link button writes the selected image URL to your clipboard only when you click it. The tool does not read your clipboard.'] },
        { heading: 'Microsoft Clarity analytics', paragraphs: ['We use Microsoft Clarity to understand visitor interactions through heatmaps and session replay. Clarity may use cookies and collect usage, device, browser, and interaction information, including information about the pages you visit and how you use them.', 'Microsoft processes this information under its own policies.'], link: { label: 'Microsoft Privacy Statement', url: 'https://privacy.microsoft.com/privacystatement' } },
        { heading: 'Hosting and site data', paragraphs: ['Cloudflare hosts this site and may process standard request logs and connection information to deliver and secure it. Hosting requests are separate from the thumbnail requests your browser sends to YouTube’s image CDN.', 'We also use Cloudflare Web Analytics to understand page visits and performance, including page-load timing and other performance metrics collected through its browser beacon. The site has no accounts or sign-in. Hosting and analytics providers process information under their own policies.'] },
        { heading: 'Google ads and data', paragraphs: ['Google ads are not currently enabled on this site. If we display ads through Google AdSense, Google and other third-party advertising providers may place or read cookies and local storage, use web beacons, and collect IP addresses, device and browser identifiers, page views, and ad interactions.', 'These providers may use and share this information to deliver ads, personalize them where permitted, measure performance, and prevent fraud. They may combine information about visits to this site with visits to other websites and apps. Google explains its data use in the link below.'], link: { label: 'How Google uses information from sites and apps', url: 'https://policies.google.com/technologies/partner-sites' } },
        { heading: 'Advertising choices and consent', paragraphs: ['You can manage Google ad personalization through My Ad Center and control or delete cookies through your browser settings. Turning off personalization does not mean that all cookies stop or that you will see no ads.', 'Where consent is required for advertising cookies or personalized ads, we will obtain it before enabling the relevant features and provide a way to withdraw it. Google ads are not currently enabled on this site.'], link: { label: 'Google My Ad Center', url: 'https://myadcenter.google.com/' } },
        { heading: 'Policy updates', paragraphs: ['If the way this tool handles data changes, this page will be updated to describe it.'] },
      ], updated: 'Last updated: October 5, 2026.',
    },
    terms: {
      title: 'Terms of Use – YT Thumbnail Downloader', description: 'Simple terms for using YT Thumbnail Downloader, including image rights, availability, and our independent status.', eyebrow: 'Terms of use', h1: 'Use the tool. Respect the work.', lead: 'YT Thumbnail Downloader is a free tool for finding thumbnail images available from YouTube’s image CDN. Please use it responsibly.',
      sections: [
        { heading: 'Image rights stay with their owners', paragraphs: ['Being able to view or download a thumbnail does not give you permission to republish it, use it commercially, or claim it as your own. Use images you own, have permission to use, or are otherwise entitled to use under the rules that apply to you.', 'You are responsible for how you use a downloaded image and for following applicable laws and platform terms.'] },
        { heading: 'Availability and limitations', paragraphs: ['The tool relies on images supplied by YouTube. A thumbnail may be unavailable, change over time, or exist only at a smaller size. Browser and network restrictions can also affect previews and downloads.', 'We aim to keep the tool useful, but do not promise uninterrupted access or a particular image resolution. Features may change as browser behavior and image availability change.'] },
        { heading: 'Reasonable use', paragraphs: ['Do not use this site to bypass access restrictions, interfere with the service, or infringe someone else’s rights. It is designed for individual thumbnail lookups and does not provide access to private videos or download video files.'] },
        { heading: 'An independent service', paragraphs: ['YT Thumbnail Downloader is not affiliated with, sponsored by, or endorsed by YouTube or Google. YouTube and other product names belong to their respective owners.'] },
      ], updated: 'Last updated: October 4, 2026.',
    },
  },
  notFound: { title: 'Page Not Found – YT Thumbnail Downloader', description: 'This page could not be found. Return to YT Thumbnail Downloader to find and save a YouTube thumbnail.', eyebrow: '404 · Page not found', h1: 'This page isn’t here.', lead: 'The address may be mistyped, or the page may have moved. The thumbnail downloader is one click away.' },
} satisfies LocaleContent;
